### ISSUE TITLE
アカウント変更機能_ユーザー情報の編集_back

### ISSUE THREAD

**Issue by kunrenyouAcount** [Invoice-ti-mukaihatu/invoice_back#12]
## 更新項目
- ユーザー名
- メールアドレス
~~- パスワード~~
- 氏名
- 住所

## どのパターンで進めるか考える
- 個別に更新のAPIを作る(5API作成)
- 全て一括で更新のAPIを作る(1API作成)
- 意味のある単位でAPIを作る(2以上のAPI作成)

**Comment by TAKA3535** [comment]
調査結果
パスワードを除くユーザー情報(ユーザー名、メールアドレス、氏名、住所)の一括編集APIとパスワードだけの編集APIの２つ作成
- パスワード以外のテキストボックスには現在登録している情報が自動入力予定
理由；全て一括編集APIだとパスワードのテキストボックスにも現在のパスワードの情報を反映させようとすると現在パスワードが見えてしまうため、パスワート編集APIを用意
